development:
  host: localhost
  database: sudoku31_development

test:
  host: localhost
  database: sudoku31_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
