require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PuzzlesController do

  # This should return the minimal set of attributes required to create a valid
  # Puzzle. As you add validations to Puzzle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    @valid_attributes = {
      :name => "Example Puzzle",
      :description => "Example Puzzle",
      :cellstring => "cell11:1,cell12:3,cell13:4",
      :level => "1"
    }  
  end

  describe "GET index" do
    it "assigns all puzzles as @puzzles" do
      puzzle = Puzzle.create! valid_attributes
      get :index
      assigns(:puzzles).should eq([puzzle])
    end
  end

  describe "GET show" do
    it "assigns the requested puzzle as @puzzle" do
      puzzle = Puzzle.create! valid_attributes
      get :show, :id => puzzle.id.to_s
      assigns(:puzzle).should eq(puzzle)
    end
  end

  describe "GET new" do
    it "assigns a new puzzle as @puzzle" do
      get :new
      assigns(:puzzle).should be_a_new(Puzzle)
    end
  end

  describe "GET edit" do
    it "assigns the requested puzzle as @puzzle" do
      puzzle = Puzzle.create! valid_attributes
      get :edit, :id => puzzle.id.to_s
      assigns(:puzzle).should eq(puzzle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Puzzle" do
        expect {
          post :create, :puzzle => valid_attributes
        }.to change(Puzzle, :count).by(1)
      end

      it "assigns a newly created puzzle as @puzzle" do
        post :create, :puzzle => valid_attributes
        assigns(:puzzle).should be_a(Puzzle)
        assigns(:puzzle).should be_persisted
      end

      it "redirects to the created puzzle" do
        post :create, :puzzle => valid_attributes
        response.should redirect_to(Puzzle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved puzzle as @puzzle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Puzzle.any_instance.stub(:save).and_return(false)
        post :create, :puzzle => {}
        assigns(:puzzle).should be_a_new(Puzzle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Puzzle.any_instance.stub(:save).and_return(false)
        post :create, :puzzle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested puzzle" do
        puzzle = Puzzle.create! valid_attributes
        # Assuming there are no other puzzles in the database, this
        # specifies that the Puzzle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Puzzle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => puzzle.id, :puzzle => {'these' => 'params'}
      end

      it "assigns the requested puzzle as @puzzle" do
        puzzle = Puzzle.create! valid_attributes
        put :update, :id => puzzle.id, :puzzle => valid_attributes
        assigns(:puzzle).should eq(puzzle)
      end

      it "redirects to the puzzle" do
        puzzle = Puzzle.create! valid_attributes
        put :update, :id => puzzle.id, :puzzle => valid_attributes
        response.should redirect_to(puzzle)
      end
    end

    describe "with invalid params" do
      it "assigns the puzzle as @puzzle" do
        puzzle = Puzzle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Puzzle.any_instance.stub(:save).and_return(false)
        put :update, :id => puzzle.id.to_s, :puzzle => {}
        assigns(:puzzle).should eq(puzzle)
      end

      it "re-renders the 'edit' template" do
        puzzle = Puzzle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Puzzle.any_instance.stub(:save).and_return(false)
        put :update, :id => puzzle.id.to_s, :puzzle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested puzzle" do
      puzzle = Puzzle.create! valid_attributes
      expect {
        delete :destroy, :id => puzzle.id.to_s
      }.to change(Puzzle, :count).by(-1)
    end

    it "redirects to the puzzles list" do
      puzzle = Puzzle.create! valid_attributes
      delete :destroy, :id => puzzle.id.to_s
      response.should redirect_to(puzzles_url)
    end
  end

end
